services:
  web:
    image: ${IMAGE_REPOSITORY}-web:${IMAGE_TAG}
    container_name: bonbonk-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/cloudflare/bonbonk:/etc/nginx/certs:ro
    depends_on:
      - php

  php:
    image: ${IMAGE_REPOSITORY}-php:${IMAGE_TAG}
    container_name: bonbonk-php
    restart: unless-stopped
    working_dir: /var/www/html

  node:
    image: ${IMAGE_REPOSITORY}-node:${IMAGE_TAG}
    container_name: bonbonk-node
    working_dir: /app
    profiles:
      - tools
    command: ["npm", "--version"]